--select * from customer limit 20

-- Q1. What is the total revenue generated by male vs. female customers?

select gender, Sum(purchase_amount) As revenue_by_gender 
From customer 
Group By gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id, purchase_amount
From customer
Where discount_applied = 'Yes'
And purchase_amount >= 
(Select Avg(purchase_amount) from customer);

-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased, ROUND(Avg(review_rating::numeric),2) as avg_product_rating
From customer
Group By item_purchased
Order By avg_product_rating DESC
LIMIT 5;

-- Q4. Compare the average Purchase amounts between Standard and Express Shipping?

select shipping_type, ROUND(Avg(purchase_amount),2) as avg_shipping_amount
From customer
Where shipping_type in ('Standard','Express')
Group By shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers?

select subscription_status, Count(customer_id) as total_customers, ROUND(Avg(purchase_amount),2) As average_spend, Sum(purchase_amount) As total_revenue
From customer
Group By subscription_status
Order By total_revenue, average_spend Desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased, ROUND(100 * SUM(Case When discount_applied = 'Yes' Then 1 Else 0 END)/Count(*),2) As discount_rate
From customer
Group by item_purchased
Order by discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

With customer_type As (
Select customer_id, previous_purchases,
CASE
    WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END As customer_segment
From Customer
)

Select customer_segment, count(*) As "Number of Customers"
From customer_type
Group By customer_segment;

-- Q8. What are the top 3 most purchased products within each category?

With item_counts as (
select category,
item_purchased,
Count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
from customer group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
Count(customer_id) as repeat_buyers
From customer
where previous_purchases > 5
Group By subscription_status;

--Q10. What is the revenue contribution of each age group?

select age_group, 
Sum(purchase_amount) as total_revenue
From customer
Group By age_group
Order By total_revenue DESC;
